# Generated by Django 6.0.5 on 2026-05-24 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ishchilar',
            table=None,
        ),
    ]
