# Generated by Django 6.0.5 on 2026-05-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_ishchilar_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ishchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('surname', models.CharField(max_length=100, verbose_name='Familiya')),
                ('age', models.IntegerField(verbose_name='Yosh')),
                ('sohasi', models.CharField(max_length=100, verbose_name='Sohasi')),
                ('rasm', models.ImageField(upload_to='rasmlar/', verbose_name='Rasm')),
                ('description', models.TextField(verbose_name="O'zi haqida")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ishchi',
                'verbose_name_plural': 'Ishchilar',
            },
        ),
        migrations.DeleteModel(
            name='ishchilar',
        ),
    ]
