# Generated by Django 5.2.5 on 2026-06-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_foydalanuvchi_alter_ishchi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='foydalanuvchi',
            name='password1',
            field=models.CharField(default='', max_length=225),
            preserve_default=False,
        ),
    ]
