# Generated by Django 5.2.5 on 2026-06-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_foydalanuvchi_password1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foydalanuvchi',
            name='password1',
        ),
        migrations.AddField(
            model_name='foydalanuvchi',
            name='password',
            field=models.CharField(default='', max_length=225),
        ),
    ]
